import { useEffect, useMemo, useState } from 'react'
import './style.css'
import { evaluateAction, defaultPolicy } from './lib/policy'
import type { AgentAction, ShieldDecision } from './lib/types'
import { scenarios } from './data/scenarios'
function App() { const [selectedId, setSelectedId] = useState(scenarios[0].id); const [customPrompt, setCustomPrompt] = useState(''); const [decision, setDecision] = useState<ShieldDecision | null>(null); const base = useMemo(() => scenarios.find((s) => s.id === selectedId) ?? scenarios[0], [selectedId]); const action: AgentAction = useMemo(() => ({ ...base, prompt: customPrompt || base.prompt }), [base, customPrompt]); useEffect(() => { evaluateAction(action).then(setDecision) }, [action]); return <main><section className="hero"><div><p className="eyebrow">Casper Agentic Buildathon 2026</p><h1>Casper AgentShield</h1><p className="subtitle">Security runtime for autonomous Casper agents. It blocks unsafe signing before wallet handoff and anchors every allow/block decision as a Casper Testnet audit proof.</p></div><div className="scorecard"><span>Decision</span><strong className={decision?.decision.toLowerCase()}>{decision?.decision ?? '...'}</strong><small>Risk score: {decision?.riskScore ?? '...'}/100</small></div></section><section className="grid two"><article className="panel"><h2>1. Agent action request</h2><label>Scenario</label><select value={selectedId} onChange={(e) => { setSelectedId(e.target.value); setCustomPrompt('') }}>{scenarios.map((s) => <option key={s.id} value={s.id}>{s.id}</option>)}</select><label>Prompt / tool request</label><textarea value={customPrompt || base.prompt} onChange={(e) => setCustomPrompt(e.target.value)} rows={7} /><div className="facts"><span>Agent <b>{action.agentId}</b></span><span>Network <b>{action.network}</b></span><span>Target <b>{action.target}</b></span><span>Method <b>{action.method}</b></span><span>Amount <b>{action.amountCSPR} CSPR</b></span></div></article><article className="panel"><h2>2. Policy firewall</h2><div className="policy"><div><span>Network allowlist</span><b>{defaultPolicy.allowedNetworks.join(', ')}</b></div><div><span>Single spend cap</span><b>{defaultPolicy.maxSingleSpendCSPR} CSPR</b></div><div><span>Review threshold</span><b>{defaultPolicy.reviewAboveRiskScore}</b></div><div><span>Block threshold</span><b>{defaultPolicy.blockAboveRiskScore}</b></div></div><h3>Findings</h3><ul className="findings">{decision?.findings.map((f) => <li key={f.rule} className={f.severity}><b>{f.rule}</b><span>{f.message}</span><em>+{f.score}</em></li>)}</ul></article></section><section className="grid three"><article className="panel proof"><h2>3. Casper audit proof</h2><p>These hashes are deterministic and ready for the Odra <code>record_decision</code> entry point.</p><Hash label="Intent" value={decision?.intentHash} /><Hash label="Policy" value={decision?.policyHash} /><Hash label="Evidence" value={decision?.evidenceHash} /><Hash label="Decision" value={decision?.decisionHash} /></article><article className="panel"><h2>4. Anchor contract</h2><pre>{`contract: AgentShieldDecisionLog
entrypoint: record_decision
network: ${action.network}
status: ${decision?.casperAnchor.status ?? '...'}`}</pre><p className="muted">For live Testnet: fund the generated public key, then run <code>bash scripts/deploy-anchor-docker.sh</code> to anchor the BLOCK decision fields from <code>deploy-args.json</code>.</p></article><article className="panel"><h2>5. Recommendation</h2><p className="recommendation">{decision?.recommendedAction}</p><p className="muted">AgentShield is designed as an MCP/x402 security tool: other Casper agents can pay per risk check, receive ALLOW/BLOCK, and prove compliance to users.</p></article></section></main> }
function Hash({ label, value }: { label: string, value?: string }) { return <div className="hash"><span>{label}</span><code>{value ?? '...'}</code></div> }
export default App
